//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GlobalEntities : DbContext
    {
        public GlobalEntities()
            : base("name=GlobalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUsers_Alternative> AspNetUsers_Alternative { get; set; }
        public virtual DbSet<Maestro_Areas> Maestro_Areas { get; set; }
        public virtual DbSet<Maestro_Editoriales> Maestro_Editoriales { get; set; }
        public virtual DbSet<Maestro_Incidencias> Maestro_Incidencias { get; set; }
        public virtual DbSet<Maestro_Incidencias_Nivel> Maestro_Incidencias_Nivel { get; set; }
        public virtual DbSet<Maestro_Incidencias_Orden> Maestro_Incidencias_Orden { get; set; }
        public virtual DbSet<Maestro_Incidencias_Orden_Areas> Maestro_Incidencias_Orden_Areas { get; set; }
        public virtual DbSet<Maestro_Incidencias_Orden_Areas_Users> Maestro_Incidencias_Orden_Areas_Users { get; set; }
        public virtual DbSet<Maestro_Incidencias_OrdenDictamen> Maestro_Incidencias_OrdenDictamen { get; set; }
        public virtual DbSet<Maestro_Incidencias_OrdenDictamenClosed> Maestro_Incidencias_OrdenDictamenClosed { get; set; }
        public virtual DbSet<Maestro_Incidencias_Seguimiento> Maestro_Incidencias_Seguimiento { get; set; }
        public virtual DbSet<Maestro_Incidencias_Seguimiento_DI> Maestro_Incidencias_Seguimiento_DI { get; set; }
        public virtual DbSet<Maestro_Orden> Maestro_Orden { get; set; }
    }
}
