//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro_Incidencias_Orden_Areas
    {
        public int id { get; set; }
        public Nullable<int> Maestro_inc_OrdenID { get; set; }
        public Nullable<int> Maestro_AreasId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    }
}
