//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maestro_Incidencias_Seguimiento_DI
    {
        public int id { get; set; }
        public Nullable<int> Maestro_Incidencias_SeguimientoId { get; set; }
        public string path { get; set; }
    }
}
