
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TicketManagement.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Maestro_Incidencias_Seguimiento_DI
{

    public int id { get; set; }

    public Nullable<int> Maestro_Incidencias_SeguimientoId { get; set; }

    public string path { get; set; }

}

}
