//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TicketManagement.Reports.Global
{

    public partial class AspNetUsers_Alternative : XPLiteObject
    {
        string fId;
        [Key]
        [Size(128)]
        public string Id
        {
            get { return fId; }
            set { SetPropertyValue<string>(nameof(Id), ref fId, value); }
        }
        string fEmail;
        [Size(256)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        bool fEmailConfirmed;
        public bool EmailConfirmed
        {
            get { return fEmailConfirmed; }
            set { SetPropertyValue<bool>(nameof(EmailConfirmed), ref fEmailConfirmed, value); }
        }
        string fPasswordHash;
        [Size(SizeAttribute.Unlimited)]
        public string PasswordHash
        {
            get { return fPasswordHash; }
            set { SetPropertyValue<string>(nameof(PasswordHash), ref fPasswordHash, value); }
        }
        string fSecurityStamp;
        [Size(SizeAttribute.Unlimited)]
        public string SecurityStamp
        {
            get { return fSecurityStamp; }
            set { SetPropertyValue<string>(nameof(SecurityStamp), ref fSecurityStamp, value); }
        }
        string fPhoneNumber;
        [Size(SizeAttribute.Unlimited)]
        public string PhoneNumber
        {
            get { return fPhoneNumber; }
            set { SetPropertyValue<string>(nameof(PhoneNumber), ref fPhoneNumber, value); }
        }
        bool fPhoneNumberConfirmed;
        public bool PhoneNumberConfirmed
        {
            get { return fPhoneNumberConfirmed; }
            set { SetPropertyValue<bool>(nameof(PhoneNumberConfirmed), ref fPhoneNumberConfirmed, value); }
        }
        bool fTwoFactorEnabled;
        public bool TwoFactorEnabled
        {
            get { return fTwoFactorEnabled; }
            set { SetPropertyValue<bool>(nameof(TwoFactorEnabled), ref fTwoFactorEnabled, value); }
        }
        DateTime fLockoutEndDateUtc;
        public DateTime LockoutEndDateUtc
        {
            get { return fLockoutEndDateUtc; }
            set { SetPropertyValue<DateTime>(nameof(LockoutEndDateUtc), ref fLockoutEndDateUtc, value); }
        }
        bool fLockoutEnabled;
        public bool LockoutEnabled
        {
            get { return fLockoutEnabled; }
            set { SetPropertyValue<bool>(nameof(LockoutEnabled), ref fLockoutEnabled, value); }
        }
        int fAccessFailedCount;
        public int AccessFailedCount
        {
            get { return fAccessFailedCount; }
            set { SetPropertyValue<int>(nameof(AccessFailedCount), ref fAccessFailedCount, value); }
        }
        string fUserName;
        [Size(256)]
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>(nameof(UserName), ref fUserName, value); }
        }
        string fApellidoPaterno;
        [Size(SizeAttribute.Unlimited)]
        public string ApellidoPaterno
        {
            get { return fApellidoPaterno; }
            set { SetPropertyValue<string>(nameof(ApellidoPaterno), ref fApellidoPaterno, value); }
        }
        string fApellidoMaterno;
        [Size(SizeAttribute.Unlimited)]
        public string ApellidoMaterno
        {
            get { return fApellidoMaterno; }
            set { SetPropertyValue<string>(nameof(ApellidoMaterno), ref fApellidoMaterno, value); }
        }
        string fNombres;
        [Size(SizeAttribute.Unlimited)]
        public string Nombres
        {
            get { return fNombres; }
            set { SetPropertyValue<string>(nameof(Nombres), ref fNombres, value); }
        }
        Maestro_Areas fMaestro_AreasId;
        [Association(@"AspNetUsers_AlternativeReferencesMaestro_Areas")]
        public Maestro_Areas Maestro_AreasId
        {
            get { return fMaestro_AreasId; }
            set { SetPropertyValue<Maestro_Areas>(nameof(Maestro_AreasId), ref fMaestro_AreasId, value); }
        }
        string fImagePath;
        [Size(SizeAttribute.Unlimited)]
        public string ImagePath
        {
            get { return fImagePath; }
            set { SetPropertyValue<string>(nameof(ImagePath), ref fImagePath, value); }
        }
    }

}
