//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TicketManagement.Reports.Global
{
    public static class ConnectionHelper
    {
        static Type[] persistentTypes = new Type[] {
            typeof(AspNetRoles),
            typeof(AspNetUserRoles),
            typeof(AspNetUsers_Alternative),
            typeof(Maestro_Areas),
            typeof(Maestro_Editoriales),
            typeof(Maestro_Incidencias),
            typeof(Maestro_Incidencias_Orden),
            typeof(Maestro_Incidencias_Orden_Areas),
            typeof(Maestro_Incidencias_Orden_Areas_Users),
            typeof(Maestro_Incidencias_OrdenDictamen),
            typeof(Maestro_Incidencias_OrdenDictamenClosed),
            typeof(Maestro_Incidencias_Seguimiento),
            typeof(Maestro_Incidencias_Seguimiento_DI),
            typeof(Maestro_Orden),
            typeof(Maestro_Orden_Descripcion),
            typeof(Maestro_Orden_Prioridad)
        };
        public static Type[] GetPersistentTypes()
        {
            Type[] copy = new Type[persistentTypes.Length];
            Array.Copy(persistentTypes, copy, persistentTypes.Length);
            return copy;
        }
        public static string ConnectionString { get { return System.Configuration.ConfigurationManager.ConnectionStrings["133.1.10.58Global"].ConnectionString; } }
        public static void Connect(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false)
        {
            if (threadSafe)
            {
                var provider = XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
                var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary();
                dictionary.GetDataStoreSchema(persistentTypes);
                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, provider);
            }
            else
            {
                XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
        }
    }

}
