//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TicketManagement.Reports.Global
{

    public partial class Maestro_Incidencias_Orden : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        int fMaestro_OrdenId;
        public int Maestro_OrdenId
        {
            get { return fMaestro_OrdenId; }
            set { SetPropertyValue<int>(nameof(Maestro_OrdenId), ref fMaestro_OrdenId, value); }
        }
        int fMaestro_IncidenciasId;
        public int Maestro_IncidenciasId
        {
            get { return fMaestro_IncidenciasId; }
            set { SetPropertyValue<int>(nameof(Maestro_IncidenciasId), ref fMaestro_IncidenciasId, value); }
        }
        DateTime fUpdated_At;
        public DateTime Updated_At
        {
            get { return fUpdated_At; }
            set { SetPropertyValue<DateTime>(nameof(Updated_At), ref fUpdated_At, value); }
        }
        DateTime fFechaCierre;
        public DateTime FechaCierre
        {
            get { return fFechaCierre; }
            set { SetPropertyValue<DateTime>(nameof(FechaCierre), ref fFechaCierre, value); }
        }
        string fUserIDAltaTk;
        [Size(128)]
        public string UserIDAltaTk
        {
            get { return fUserIDAltaTk; }
            set { SetPropertyValue<string>(nameof(UserIDAltaTk), ref fUserIDAltaTk, value); }
        }
    }

}
