//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TicketManagement.Reports.Global
{

    public partial class Maestro_Incidencias_Seguimiento : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fObservaciones;
        [Size(SizeAttribute.Unlimited)]
        public string Observaciones
        {
            get { return fObservaciones; }
            set { SetPropertyValue<string>(nameof(Observaciones), ref fObservaciones, value); }
        }
        string fUserId;
        [Size(128)]
        public string UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<string>(nameof(UserId), ref fUserId, value); }
        }
        DateTime fUpdated_At;
        public DateTime Updated_At
        {
            get { return fUpdated_At; }
            set { SetPropertyValue<DateTime>(nameof(Updated_At), ref fUpdated_At, value); }
        }
        int fMaestro_Incidencias_Orden_Areas_UsersId;
        public int Maestro_Incidencias_Orden_Areas_UsersId
        {
            get { return fMaestro_Incidencias_Orden_Areas_UsersId; }
            set { SetPropertyValue<int>(nameof(Maestro_Incidencias_Orden_Areas_UsersId), ref fMaestro_Incidencias_Orden_Areas_UsersId, value); }
        }
    }

}
