//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TicketManagement.Reports.Global
{

    public partial class Maestro_Incidencias_Seguimiento_DI : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        int fMaestro_Incidencias_SeguimientoId;
        public int Maestro_Incidencias_SeguimientoId
        {
            get { return fMaestro_Incidencias_SeguimientoId; }
            set { SetPropertyValue<int>(nameof(Maestro_Incidencias_SeguimientoId), ref fMaestro_Incidencias_SeguimientoId, value); }
        }
        string fpath;
        [Size(SizeAttribute.Unlimited)]
        public string path
        {
            get { return fpath; }
            set { SetPropertyValue<string>(nameof(path), ref fpath, value); }
        }
    }

}
