//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TicketManagement.Reports.Global
{

    public partial class Maestro_Incidencias_OrdenDictamenClosed : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        int fMaestro_Incidencias_OrdenDictamenId;
        public int Maestro_Incidencias_OrdenDictamenId
        {
            get { return fMaestro_Incidencias_OrdenDictamenId; }
            set { SetPropertyValue<int>(nameof(Maestro_Incidencias_OrdenDictamenId), ref fMaestro_Incidencias_OrdenDictamenId, value); }
        }
        int fMaestro_OrdenId;
        public int Maestro_OrdenId
        {
            get { return fMaestro_OrdenId; }
            set { SetPropertyValue<int>(nameof(Maestro_OrdenId), ref fMaestro_OrdenId, value); }
        }
    }

}
