//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TicketManagement.Reports.Global
{

    public partial class Maestro_Incidencias_Orden_Areas : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        int fMaestro_AreasId;
        public int Maestro_AreasId
        {
            get { return fMaestro_AreasId; }
            set { SetPropertyValue<int>(nameof(Maestro_AreasId), ref fMaestro_AreasId, value); }
        }
        DateTime fUpdated_At;
        public DateTime Updated_At
        {
            get { return fUpdated_At; }
            set { SetPropertyValue<DateTime>(nameof(Updated_At), ref fUpdated_At, value); }
        }
        string fUserIDAltaTk;
        [Size(128)]
        public string UserIDAltaTk
        {
            get { return fUserIDAltaTk; }
            set { SetPropertyValue<string>(nameof(UserIDAltaTk), ref fUserIDAltaTk, value); }
        }
        int fMaestro_Incidencias_OrdenId;
        public int Maestro_Incidencias_OrdenId
        {
            get { return fMaestro_Incidencias_OrdenId; }
            set { SetPropertyValue<int>(nameof(Maestro_Incidencias_OrdenId), ref fMaestro_Incidencias_OrdenId, value); }
        }
    }

}
