//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace TicketManagement.Reports.Global
{

    public partial class Maestro_Orden : XPLiteObject
    {
        int fid;
        [Key(true)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fNombre;
        [Size(SizeAttribute.Unlimited)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        int fMaestro_EditorialesId;
        public int Maestro_EditorialesId
        {
            get { return fMaestro_EditorialesId; }
            set { SetPropertyValue<int>(nameof(Maestro_EditorialesId), ref fMaestro_EditorialesId, value); }
        }
        string fUserId;
        [Size(128)]
        public string UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<string>(nameof(UserId), ref fUserId, value); }
        }
        DateTime fUpdated_At;
        public DateTime Updated_At
        {
            get { return fUpdated_At; }
            set { SetPropertyValue<DateTime>(nameof(Updated_At), ref fUpdated_At, value); }
        }
        bool fIsReadyForWork;
        public bool IsReadyForWork
        {
            get { return fIsReadyForWork; }
            set { SetPropertyValue<bool>(nameof(IsReadyForWork), ref fIsReadyForWork, value); }
        }
        bool fIsClosed;
        public bool IsClosed
        {
            get { return fIsClosed; }
            set { SetPropertyValue<bool>(nameof(IsClosed), ref fIsClosed, value); }
        }
        bool fIsClosed_Successfully;
        public bool IsClosed_Successfully
        {
            get { return fIsClosed_Successfully; }
            set { SetPropertyValue<bool>(nameof(IsClosed_Successfully), ref fIsClosed_Successfully, value); }
        }
        int fMaestro_Orden_PrioridadId;
        public int Maestro_Orden_PrioridadId
        {
            get { return fMaestro_Orden_PrioridadId; }
            set { SetPropertyValue<int>(nameof(Maestro_Orden_PrioridadId), ref fMaestro_Orden_PrioridadId, value); }
        }
        bool fisticket_cancelled;
        public bool isticket_cancelled
        {
            get { return fisticket_cancelled; }
            set { SetPropertyValue<bool>(nameof(isticket_cancelled), ref fisticket_cancelled, value); }
        }
        string fIsClosed_UserId;
        [Size(128)]
        public string IsClosed_UserId
        {
            get { return fIsClosed_UserId; }
            set { SetPropertyValue<string>(nameof(IsClosed_UserId), ref fIsClosed_UserId, value); }
        }
        DateTime fIsClosed_Timestamp;
        public DateTime IsClosed_Timestamp
        {
            get { return fIsClosed_Timestamp; }
            set { SetPropertyValue<DateTime>(nameof(IsClosed_Timestamp), ref fIsClosed_Timestamp, value); }
        }
        string fIsClosed_Successfully_UserId;
        [Size(128)]
        public string IsClosed_Successfully_UserId
        {
            get { return fIsClosed_Successfully_UserId; }
            set { SetPropertyValue<string>(nameof(IsClosed_Successfully_UserId), ref fIsClosed_Successfully_UserId, value); }
        }
        DateTime fIsClosed_Successfully_Timestamp;
        public DateTime IsClosed_Successfully_Timestamp
        {
            get { return fIsClosed_Successfully_Timestamp; }
            set { SetPropertyValue<DateTime>(nameof(IsClosed_Successfully_Timestamp), ref fIsClosed_Successfully_Timestamp, value); }
        }
        string fisticket_cancelled_UserId;
        [Size(128)]
        public string isticket_cancelled_UserId
        {
            get { return fisticket_cancelled_UserId; }
            set { SetPropertyValue<string>(nameof(isticket_cancelled_UserId), ref fisticket_cancelled_UserId, value); }
        }
        DateTime fisticket_cancelled_Timestamp;
        public DateTime isticket_cancelled_Timestamp
        {
            get { return fisticket_cancelled_Timestamp; }
            set { SetPropertyValue<DateTime>(nameof(isticket_cancelled_Timestamp), ref fisticket_cancelled_Timestamp, value); }
        }
    }

}
